FROM node:17-alpine3.15
ENV NUXT_HOST=0.0.0.0 NUXT_PORT=3000
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . /usr/src/nuxt-app/
RUN yarn install
RUN yarn build
EXPOSE 3000
CMD [ "yarn", "start" ]
